# Docker Compose configuration

# Database - connect to MySQL container
quarkus.datasource.db-kind=mysql
quarkus.datasource.reactive.url=mysql://journal-mysql:3306/patient_system
quarkus.datasource.username=root
quarkus.datasource.password=admin

# Keycloak - Docker container
quarkus.oidc.auth-server-url=http://keycloak:8080/realms/journal-realm
quarkus.oidc.client-id=backend-service
